[general]
import = ["~/AppData/Roaming/alacritty/theme.toml"]

[window]
opacity = 0.85
padding = { x = 10, y = 10 }
dimensions = { columns = 126, lines = 42 }
decorations = "full"
dynamic_padding = true

[font]
size = 13.0
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold   = { family = "Hack Nerd Font Mono", style = "Bold" }
italic = { family = "Hack Nerd Font Mono", style = "Italic" }

[scrolling]
history = 10000
